[package]
name = "foxbox_users"
version = "0.1.0"
authors = ["Fernando Jiménez Moreno <ferjmoreno@gmail.com>", "Salvador de la Puente González <salva@unoyunodiez.com"]

[dependencies]
iron = "*"
jwt = "0.4.0"
libc = "*"
rand = "0.3.14"
router = "*"
rustc-serialize = "*"
rusqlite = "*"
rust-crypto = "*"
unicase = "*"
urlencoded = "0.2.1"

[dev-dependencies]
iron-test = "*"
stainless = "0.1.4"
clippy = "0.0.48"
