[package]
name = "foxbox_users"
version = "0.1.0"
authors = ["Fernando Jim√©nez Moreno <ferjmoreno@gmail.com>"]

[dependencies]
iron = "*"
iron-test = "*"
libc = "*"
router = "*"
rustc-serialize = "*"
rusqlite = "*"
rust-crypto = "*"
unicase = "*"
stainless = { git = "https://github.com/reem/stainless.git", rev = "82392f2e" }
rand = "0.3.14"
